namespace lilToon.URP.Extensions.PostProcessing
{
    public enum ShoostPostProcessEffect
    {
        CustomMaterial = 0,
        AutoWhiteBalance,
        ChangeFrameRate,
        ColorGradingCustom,
        CRTEffects,
        Distortion,
        DitheringCustom,
        DownScaleResolution,
        FilmBreathGateWeave,
        Fisheye,
        GateWeave,
        GrainCustom,
        IrisBlur,
        RemovedEffectSlot13,
        LensDistortionCustom,
        LevelAdjustment,
        MotionTrail,
        Pixelize,
        RGBBlur,
        RGBBlurV2,
        RGBChannelSeparator,
        RGBSplit,
        SharpenBefore,
        SharpenAfter,
        Tube,
        VignetteCustom,
        RetroLookProBleedCustom,
        RetroLookProNoise2Custom,
        RetroLookProOldFilm2Custom,
        RetroLookProTVEffectCustom,
        RemovedEffectSlot30,
        RemovedEffectSlot31,
        RemovedEffectSlot32,
        Gradient,
        Glow,
        Lighting,
        CenterColorCorrection,
        LED,
        Weather,
        Particle,
        CameraSwitcher,
        TransparentBackground,
        VHS,
        CameraFlash,
        ToonMap,
        Kuwahara,
        BokehZoomBlur,
        ApertureBokeh,
        LensFlare,
        CinematicBars,
        GlitchArt,
        PrismFracture,
        SpeedLines,
        SkyGodRays
    }

    public enum ShoostPostProcessBlendMode
    {
        Normal = 0,
        Add = 1,
        Multiply = 2,
        Screen = 3,
        Darken = 4,
        ColorBurn = 5,
        LinearBurn = 6,
        Lighten = 7,
        ColorDodge = 8,
        Overlay = 9,
        SoftLight = 10,
        HardLight = 11,
        VividLight = 12,
        LinearLight = 13,
        PinLight = 14,
        HardMix = 15,
        Difference = 16,
        Exclusion = 17,
        Subtract = 18,
        Divide = 19,
        Hue = 20,
        Saturation = 21,
        Color = 22,
        Luminosity = 23
    }

}
